name: Pull Request Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Compile Java files
        run: javac -d . src/Test.java  
     # - name: Run tests
     #   run: java -cp . org.junit.runner.JUnitCore com.example.MyTestSuite 
